version: '3.3'

services:
  webserver:
    build:
      context: ./bin/webserver
      args:
        BX_UID: 1000
        BX_GID: 1000
    container_name: '7.2.x-webserver'
    restart: 'no'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${CONFIG_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    command: --explicit_defaults_for_timestamp
    build: ./bin/mysql
    container_name: '5.7-mysql'
    restart: 'no'
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_DATABASE: sprint
      MYSQL_PASSWORD: bitrix
      MYSQL_ROOT_PASSWORD: bitrix
      MYSQL_USER: bitrix
